server:
    port: ${PORT:8081}

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      preferSameZoneEureka: true
    registryFetchIntervalSeconds: 10
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 3
    disable-delta: true
    
spring:
  rabbitmq:
    addresses: 192.168.99.100
    port: 5672
    username: guest
    password: guest
 
management:
  endpoints:
     web:
       exposure:
         include: "refresh"
  security:
    enabled: false

sample:
  string:
    property: Client Application
  int:
    property: 3